const videoAttributes = {
    preload: true,
    controls: true,
    autoPlay: true,
}

export const winsData = [
    // ! Videos
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-1.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-1.png',
        size: '1080-1920',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-1.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-2.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-2.png',
        size: '1280-720',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-2.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-3.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-3.png',
        size: '480-480',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-3.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-4.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-4.png',
        size: '480-848',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-4.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-5.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-5.png',
        size: '888-1920',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-5.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-6.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-6.png',
        size: '446-576',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-6.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    {
        type: 'video',
        src: '/assets/testimonials/videos/video-7.mp4',
        poster: '/assets/testimonials/videos/posters/video-poster-7.png',
        size: '886-726',
        subHtml: 'Video Testimonial',
        video: {
            source: [{ src: '/assets/testimonials/videos/video-7.mp4', type: 'video/mp4' }],
            attributes: videoAttributes,
        },
    },
    // * Images
    {
        type: 'image',
        src: '/assets/testimonials/images/image-1.jpg',
        thumb: '/assets/testimonials/images/image-1.jpg',
        size: '3024-4032',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-2.jpg',
        thumb: '/assets/testimonials/images/image-2.jpg',
        size: '1179-1823',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-3.jpg',
        thumb: '/assets/testimonials/images/image-3.jpg',
        size: '1179-1451',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-4.jpg',
        thumb: '/assets/testimonials/images/image-4.jpg',
        size: '1179-1387',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-5.jpg',
        thumb: '/assets/testimonials/images/image-5.jpg',
        size: '1179-2019',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-6.jpg',
        thumb: '/assets/testimonials/images/image-6.jpg',
        size: '1179-1872',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-7.jpg',
        thumb: '/assets/testimonials/images/image-7.jpg',
        size: '1179-665',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-8.jpg',
        thumb: '/assets/testimonials/images/image-8.jpg',
        size: '1179-655',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-9.jpg',
        thumb: '/assets/testimonials/images/image-9.jpg',
        size: '1179-1125',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-10.jpg',
        thumb: '/assets/testimonials/images/image-10.jpg',
        size: '1179-1078',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-11.jpg',
        thumb: '/assets/testimonials/images/image-11.jpg',
        size: '1179-1080',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-12.jpg',
        thumb: '/assets/testimonials/images/image-12.jpg',
        size: '1179-1100',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-13.jpg',
        thumb: '/assets/testimonials/images/image-13.jpg',
        size: '1179-1072',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-14.jpg',
        thumb: '/assets/testimonials/images/image-14.jpg',
        size: '1179-1080',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-15.jpg',
        thumb: '/assets/testimonials/images/image-15.jpg',
        size: '1179-1111',
        subHtml: 'Image',
    },
    {
        type: 'image',
        src: '/assets/testimonials/images/image-16.jpg',
        thumb: '/assets/testimonials/images/image-16.jpg',
        size: '1179-1097',
        subHtml: 'Image',
    },
]
